ARG BUILD_IMAGE=mcr.microsoft.com/azure-functions/node:4-node22-appservice
ARG SERVE_IMAGE=mcr.microsoft.com/azure-functions/python:4-python3.11-appservice

# Set Production Build Flag
ARG PROD_BUILD=true

FROM $BUILD_IMAGE AS builder

# Production Build Flag
ARG PROD_BUILD

# Set Debian Frontend Flag
ARG DEBIAN_FRONTEND=noninteractive

# Disable NPM Update Notifications
ENV NPM_CONFIG_UPDATE_NOTIFIER=false

# Set the Working Directory
WORKDIR /tmp

# Copy UI Code
COPY ./ui/. ./

# Install UI Dependencies
RUN if [ "${PROD_BUILD}" = true ]; then \
  npm ci; \
else \
  npm install; \
fi
RUN chmod 777 -R node_modules

# Build IPAM UI
RUN npm run build

FROM $SERVE_IMAGE

# Set Production Build Flag
ARG PROD_BUILD

# Set Debian Frontend to Non-Interactive
ARG DEBIAN_FRONTEND=noninteractive

# Set Azure Function Root Directory & Enable Console Logging
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

# Disable PIP Root Warnings
ENV PIP_ROOT_USER_ACTION=ignore

# Set Working Directory
WORKDIR /tmp

# Copy Requirements File
COPY ./engine/requirements.txt .
COPY ./engine/requirements.lock.txt .

# Upgrade PIP
RUN pip install --upgrade pip --progress-bar off

# Install Dependencies
RUN if [ "${PROD_BUILD}" = true ]; then \
  pip install --no-cache-dir -r ./requirements.lock.txt --progress-bar off; \
else \
  pip install --no-cache-dir -r ./requirements.txt --progress-bar off; \
fi

# Copy Application Code to Function App Root Directory
COPY ./engine/. /home/site/wwwroot
COPY --from=builder /tmp/dist /home/site/wwwroot/dist
