ARG BUILD_IMAGE=registry.access.redhat.com/ubi8/nodejs-22
ARG SERVE_IMAGE=registry.access.redhat.com/ubi8/python-311

# Set Production Build Flag
ARG PROD_BUILD=true

# Set Default Port
ARG PORT=8080

FROM $BUILD_IMAGE AS builder

# Production Build Flag
ARG PROD_BUILD

# Disable NPM Update Notifications
ENV NPM_CONFIG_UPDATE_NOTIFIER=false

# Set the Working Directory
WORKDIR /tmp

# Switch to Root User
USER root

# Copy UI Code
COPY ./ui/. ./

# Install UI Dependencies
RUN if [ "${PROD_BUILD}" = true ]; then \
  npm ci; \
else \
  npm install; \
fi
RUN chmod 777 -R node_modules

# Build IPAM UI
RUN npm run build

FROM $SERVE_IMAGE

# Set Production Build Flag
ARG PROD_BUILD

# Port to Listen On
ARG PORT

# Set Environment Variable
ENV PORT=${PORT}

# Disable PIP Root Warnings
ENV PIP_ROOT_USER_ACTION=ignore

# Set Working Directory
WORKDIR /tmp

# Switch to Root User
USER root

# Disable Subscription Manager YUM Plugin
RUN sed -i s/enabled=./enabled=0/g /etc/yum/pluginconf.d/subscription-manager.conf

# Install OpenSSH and set the password for root to "Docker!"
RUN yum update -y
RUN yum install -qq openssh-server -y \
      && echo "root:Docker!" | chpasswd \
      && systemctl enable sshd

# Enable SSH root login with Password Authentication
# RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

# Copy 'sshd_config File' to /etc/ssh/
COPY sshd_config /etc/ssh/

RUN ssh-keygen -A
RUN mkdir /var/run/sshd

# Set Working Directory
WORKDIR /ipam

# Install Engine Dependencies
COPY ./engine/requirements.txt /code/requirements.txt
COPY ./engine/requirements.lock.txt /code/requirements.lock.txt

# Upgrade PIP
RUN pip install --upgrade pip --progress-bar off

# Install Dependencies
RUN if [ "${PROD_BUILD}" = true ]; then \
  pip install --no-cache-dir -r /code/requirements.lock.txt --progress-bar off; \
else \
  pip install --no-cache-dir -r /code/requirements.txt --progress-bar off; \
fi

# Copy Engine Code
COPY ./engine/app ./app
COPY --from=builder /tmp/dist ./dist

# Copy Init Script
COPY ./init.sh .

# Set Script Execute Permissions
RUN chmod +x init.sh
RUN chown -R 1001:0 /ipam
RUN chown -R 1001:0 /etc/profile

# Switch to Standard User
USER 1001

# Expose Ports
EXPOSE $PORT 2222

# Execute Startup Script
ENTRYPOINT ./init.sh ${PORT}
