ARG BASE_IMAGE=python:3.11-slim
FROM $BASE_IMAGE

# Set Default Port
ARG PORT=80

# Set Debian Frontend to Non-Interactive
ARG DEBIAN_FRONTEND=noninteractive

# Set Environment Variable
ENV PORT=${PORT}

# Disable PIP Root Warnings
ENV PIP_ROOT_USER_ACTION=ignore

# Set the Working Directory
WORKDIR /ipam

# Copy Requirements File
ADD ./requirements.lock.txt .

# Upgrade PIP
RUN pip install --upgrade pip --progress-bar off

# Install Dependencies
RUN pip install --no-cache-dir -r ./requirements.lock.txt --progress-bar off

# Copy Application Scripts & Sources
ADD ./app ./app
ADD ./init.sh .

# Set Script Execute Permissions
RUN chmod +x init.sh

# Expose Port
EXPOSE $PORT

# Execute Startup Script
ENTRYPOINT ./init.sh ${PORT}
